<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SolodyAuth\Module'                        => __DIR__ . '/Module.php',
    'SolodyAuth\Controller\IndexController' => __DIR__ . '/src/SolodyAuth/Controller/IndexController.php',
    'SolodyAuthTest\Framework\TestCase'        => __DIR__ . '/tests/SolodyAuth/Framework/TestCase.php',
    'SolodyAuthTest\SampleTest'                => __DIR__ . '/tests/SolodyAuth/SampleTest.php',
);
