<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Solody - Everybody is musician.'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile('http://api.map.baidu.com/api?v=2.0&ak=GVzGBMroAG7ftvkMSGs7m6jL')
        ; ?>

    </head>
    <body>
        
        <div class="container">
            <header>
                <div><img src="/img/logo.png"><span id="city"></span></div>
            </header>
            <div>
            <div id="bdmap" style="width: 100%; height:300px;"></div>
            <script type="text/javascript">

            var l = new BMap.LocalCity();
            l.get(function(rs){
                $('#city').text('您位于'+rs.name);


                var map = new BMap.Map("bdmap");
                var point = new BMap.Point(rs.center.lng, rs.center.lat);
                map.centerAndZoom(point, 15);

                
                var marker = new BMap.Marker(point);
                map.addOverlay(marker);

                var label = new BMap.Label("<p>使用浏览器定位功能，在百度地图上显示浏览者的位置。<br><br><h3>大C，网络定位找出我们在这里！</h3></p>",{offset:new BMap.Size(20,-10)});
                marker.setLabel(label); //添加百度label
                map.setCenter(point);
                marker.setAnimation(BMAP_ANIMATION_BOUNCE);
                
            	console.log(rs);
                });
            
            </script>
            </div>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Solody Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
