<div style="border:3px dashed #eee; padding:5px;  margin:20px 0; ">
<div style="height:300px; overflow: hidden;"><div id="bdmap" style="height:330px;"></div></div>
<script type="text/javascript">

var l = new BMap.LocalCity();
l.get(function(rs){
	
    $('.city_lable').text(rs.name);
    $('#local').css('display','inline');


    var map = new BMap.Map("bdmap");
    var point = new BMap.Point(rs.center.lng, rs.center.lat);
    map.centerAndZoom(point, rs.level);

    
    var marker = new BMap.Marker(point);
    map.addOverlay(marker);

    var label = new BMap.Label("您在这里！",{offset:new BMap.Size(20,-10)});
    marker.setLabel(label); //添加百度label
    map.setCenter(point);
    marker.setAnimation(BMAP_ANIMATION_BOUNCE);
    
	console.log(rs);
    });

</script>
</div>

<div>
<h4>在<span class="city_lable"></span>找到<span>35</span>个演出</h4>
<ol>
<li>正佳广场</li>
</ol>
</div>


<!-- <div class="jumbotron">
    <h2><?php echo sprintf($this->translate('Discover %sThe Best Man%s For Your Band !'), '<span class="zf-green">', '</span>') ?></h2>
    <p><?php echo sprintf(
        $this->translate('You can browse the %sInstruments Book%s, Or Make a Conversation whith the man you interested.'),
        '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">',
        '</a>') ?></p>
    <p><a class="btn btn-success btn-lg" href="/register" target="_blank"><?php echo $this->translate('How To Begin') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div> -->
